name: xrghost
description: "The ghost project - kayode olalere web portfolio."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
 # flutter packages
  cupertino_icons: ^1.0.8

 # firebase packages
  firebase_core: ^3.10.1

 # google packages##
  google_fonts: ^6.2.1

 # general packages
  build_runner: ^2.4.14
  fl_chart: ^0.70.2
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.4
  freezed: ^2.5.8
  go_router: ^14.7.2
  hooks_riverpod: ^2.6.1
  responsive_framework: ^1.5.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg
